# This workflow will publish to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Publish

on:
# Uncomment once works
#  release:
#    types: [created]
  push

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/jordanplayz158/zeroc-docker-image:v3.7.10
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Get Ice File
      run: curl -s https://raw.githubusercontent.com/mumble-voip/mumble/${GITHUB_REF#refs/*/}/src/murmur/MumbleServer.ice -o MumbleServer.ice

    - name: Get Slice Libraries? (Not sure what to call them but SliceChecksumDict.ice is required)
      run: git clone --no-checkout https://github.com/zeroc-ice/ice && cd ice && git sparse-checkout init && git sparse-checkout set slice && git checkout v3.7.10

    - name: Slice To Java
      run: slice2java -Iice/slice MumbleServer.ice

    - uses: actions/upload-artifact@v4
      with:
        path: MumbleServer

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
